trigger:
  branches:
    include:
      - main

jobs:
- job: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'dockerApi'
        dockerfile: '$(Build.SourcesDirectory)/dockerApi/Dockerfile'
        containerRegistry: 'arnoldregistry.azurecr.io'
        tags: 'main'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'dockerApp'
        dockerfile: '$(Build.SourcesDirectory)/dockerApp/Dockerfile'
        containerRegistry: 'arnoldregistry.azurecr.io'
        tags: 'main'

    - script: |
        az container create --resource-group arnoldcontainer --name multiContainerGroup --image arnoldregistry.azurecr.io/dockerApi:main arnoldregistry.azurecr.io/dockerApp:main --registry-login-server arnoldregistry.azurecr.io --registry-username "$(arnoldregistry)" --registry-password "$(1xV6E1K/66R/ET3HojnHDt1moDdZX020w9C8z4wceh+ACRBiPMtK)"
      displayName: 'Deploy multi-container group'
