trigger:
  branches:
    include:
      - main
jobs:
- job: BuildAndDeploy
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: Docker@2
    displayName: 'Build and push dockerApi image'
    inputs:
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/dockerApi/Dockerfile'
      imageName: 'myacr.azurecr.io/dockerApi:$(Build.BuildId)'
      containerRegistry: 'myacr'

  - task: Docker@2
    displayName: 'Build and push dockerApp image'
    inputs:
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/dockerApp/Dockerfile'
      imageName: 'myacr.azurecr.io/dockerApp:$(Build.BuildId)'
      containerRegistry: 'myacr'

  - script: |
      az container create --resource-group arnoldcontainer --name multiContainerGroup --image myacr.azurecr.io/dockerApi:$(Build.BuildId) myacr.azurecr.io/dockerApp:$(Build.BuildId) --registry-login-server myacr.azurecr.io --registry-username $(ACR_USERNAME) --registry-password $(ACR_PASSWORD)
    displayName: 'Deploy multi-container group'
