services:
  dockerapp:
    build:
      context: ./dockerApp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks:
      - docknet
    
  dockerapi:
    build:
      context: ./dockerApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - docknet
    
networks:
  docknet:
